pluginFormats:
  - {
      path: C:/Program Files/Steinberg/VSTPlugins/Universal Audio,
      extension: .dll,
      name: VST2,
    }
  - {
      path: C:\Program Files\Steinberg\VSTPlugins\Universal Audio\UAD Mono,
      extension: (m).dll,
      name: VST2 (Mono),
    }
  - {
      path: C:/Program Files/Common Files/VST3/Universal Audio,
      extension: .vst3,
      name: VST3,
    }
  - {
      path: C:/Program Files/Common Files/Avid/Audio/Plug-ins/Universal Audio,
      extension: .aaxplugin,
      name: AAX,
    }
  - {
      path: C:/Program Files/Universal Audio/Powered Plugins/UAD-2 Powered Plugins,
      extension: .dll,
      name: Console,
    }
