files:
  UADSystemProfile: ./configs/UADSystemProfile.txt
pluginFormats:
  - {
      path: /Library/Audio/Plug-Ins/VST/Universal Audio,
      extension: .vst,
      name: VST2,
    }
  - {
      path: /Library/Audio/Plug-Ins/VST/Universal Audio/UAD Mono,
      extension: (m).vst,
      name: VST2 (Mono),
    }
  - {
      path: /Library/Audio/Plug-ins/VST3/Universal Audio,
      extension: .vst3,
      name: VST3,
    }
  - {
      path: /Library/Application Support/Avid/Audio/Plug-Ins/Universal Audio,
      extension: .aaxplugin,
      name: AAX,
    }
  - {
      path: /Library/Audio/Plug-Ins/Components,
      etension: .component,
      name: Audio Units,
    }
  - {
      path: /Library/Application Support/Universal Audio/UAD-2 Powered Plugins,
      extension: .vst,
      name: Console,
    }
